---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticker-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticker
  template:
    metadata:
      labels:
        app: ticker
    spec:
      volumes:
        - name: ephemeral-shared-dir # used by ticker-generator and ticker-server
          emptyDir: {}
        # - name: persistent-shared-dir # used by pingpong and ticker-server
        #   persistentVolumeClaim:
        #     claimName: dwk-storage-claim
      containers:
        - name: ticker-generator
          image: mtuomiko/ticker-generator:0.0.1
          volumeMounts:
          - name: ephemeral-shared-dir
            mountPath: "/ephemeral-shared"
          envFrom:
            - configMapRef:
                name: ticker-config
        - name: ticker-server
          image: mtuomiko/ticker-server:0.0.3
          volumeMounts:
          - name: ephemeral-shared-dir
            mountPath: "/ephemeral-shared"
          # - name: persistent-shared-dir
          #   mountPath: "/persistent-shared"
          env:
          - name: COUNT_URI
            value: "http://pingpong-svc:5001/count"
          envFrom:
            - configMapRef:
                name: ticker-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticker-config
data:
  STATUS_FILE: "/ephemeral-shared/status.json"
  # COUNT_FILE: "/persistent-shared/count.json"
