apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exercises-secret
  namespace: exercises
spec:
  encryptedData:
    DB_PASSWORD: AgA66MI5WS5usOdZvIHWvrFScKIbt26Gn2xp7VPWzsuUO8WB/fEVK/nZqNfY8aouDo3dfR7b+8j7tjiSJTm/YDHyXNcVRifrdN/NKmdtsLVktRbEoTRpb9dFmk27AGjia7M4yDfpOnUVFpiV8xvuE1sDuXzIxMQRAGm0TFzCUD9ws7kBb/lJzHl7R27DyNMzzrlEWhfZRLZEtBp7xD5dQ1avjA1lHJQWzRNISDjeeSqE7x6+quyiZi74LboFhBHpR0//2M2ruoXbyH6+XyBras9hbzqS/IQYjB/9Q0EptTbTWADoF2Q6Sq30qgj6h7wXQeOvY/Wxx4tFty84HrWgQW44JcuCnVC++V+7qX4lyKpfxMgMRiUgPnkarTB4CPgre0NmWHIZNRNizRsP3qMxPm/vQniUMSqP/3dDtn/tq5KUeZ89xyt7yEVZwO+vmUrlqfhiWRg9GozxQTYnoXOH5/ufZeg5NFCwX4qsDom2BCb2PnvhbJSSvcOubFRaBeSjrw05hW8Q/XjZS4znjv9KBo7vRMlaIrmcmzRW/wDVsU+xyYcsb2YeY3Zf9fSrUceBpJbwzl4tNh3IpzpvN4lIWM2+kilC3qS7acu5/I7j43VQjRTmtpeRLX4erQg095rw8oj5nuSB9zSVT8jDSrg2MfbNYpSiqfjNZQyGypHR2MpSv9ZJ0fwQuriZUQF0LU2n3UawhV1cDFpRotqdvUtXMaxplMM=
  template:
    metadata:
      creationTimestamp: null
      name: exercises-secret
      namespace: exercises

