apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: project-secret
  namespace: project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAylKmneQGoxfvQIJP4rF0Ot4bL0vo1kpFC9o4krBckcEy66VwXzPp79g3LproVjMBgYw55TLq40RnXyFwOckf9pPbHJaDzWzhElRNmdGKj1/yA/10kcqCzKtsKOlNrmGCVjSBZZcfr4PPfEwpKegXLD6QfeVPJpdgcKa0Ek+rhOSFWSAOTi9Rh+VNBHboupJj31172JZIlfZ/ijLHafWa3wxOONUX1cqdYaWnt1NAe3nrxB1HuhPkG/PF6/4zRsT/jnrBNP/7BKAvouxvVJ+9P2mzBw2REkRhhUKlpQNbemmwYCgrUvtynOa55yVr6TqZ2+i3p7B+DK9P9weszEe46rPPZQWLMHipxQ18doYaseAN4rWdd4RA4YSwrihc0XKRreKVkBqL6A9v9UHeY0EoEvBNj+A//KsMH2wGcfBAbPFyKHtVAJCIxcxqsmULs23KI1SrspYPby2+6bdEB/GmlLlLMRf+/gADVUjp7RXLbig1+40l6EiAKfd21E2bi5PA09kpHfEGCy2S+UIXrGWyZ1hiw1Dj8P58K4X+0Dbw/dPoMv7/oV4w+5/B2DRCUTuHlv/tpdPXoBuN+tFJQsG8vGS+gh0xkp65+E7q0450r5o4hVU8P3VNa8XxnfgS5uqKbN6yj9hSH+QDDNyIxkq8LyHclJcsu3NJi8V44Eirpor701gIQvPbccZrGB/URMRzPDDCRSXdI3b7dfw4ZDAo=
    TELEGRAM_BOT_TOKEN: AgBEJZv6VOTNsjyNItQr0wzcgR7sWX5PGYqS8jitld7mRAmbqEwcToARR6jzXJGzAClRT9/lcFl8nW65EQ2G91+lWQdKePFYP3tw5Ibv5bEAG3HmCqtzAd/vTMjRej84VAInJVoSHtRdqcklz7aeX6NYAn7YglIrKSNibSztv3ut/41/E66eENa2g5sx8an+tP5G50Qtmo/O4NJVBqoIly3mqYbW/jziicA139wVkXGnEodLMVdeKScmVqBjqsenCK4cRZZltNA8QmB+I3jCfzyPfKjzwHlb3f8ALfFaXFSljENNera3AHi7cLhkUIdzWQqJ5YG4VX+yHyqe1zAtX3hLpQ9r561xeEV7bWAouM96aAo5KJTBKS/3mwMBlbGQaGHNgV3Dn6XIqFbNPxmdxtXCBspzqUeXRg0z7rdL623jsq+ijeepY4LppL+qdIAnLQkIXcz/PX1JhMbSPzo9cvAQfauhEnEsCwmHl7vDe1sfqGpiYZjDSMJOCXh40TNCbERNg7sp7EKhOWc+ayH7SHutEXPp8IuK799KGTeNoAd/FF/Dts8hQe8aH2mKcIjKc7BrNMBbOZFn09v6S4Qy+ZjHKJtbvLJn2zHVfTXIA5PVah3JQLUFkwJQmT90AOcctcgOZrYBL3bm6BtTktlqpv2rcIE7SlurWoDxnOBmQwFTJLOex0G1bqGHTADY9HNYqWQn7TA+iBl4+n1btSSPRLhc7IYMje8fmN5O4Bg9cHN5wpJCF4KDPnGC8Kr6xJpq
  template:
    metadata:
      creationTimestamp: null
      name: project-secret
      namespace: project

