apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dogcat-backend-mon
  namespace: prometheus
spec:
  namespaceSelector:
    matchNames:
      - assignment
  selector:
    matchLabels:
      app: dogcat-backend
  podMetricsEndpoints:
  - port: web