apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-frontend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-frontend
  template:
    metadata:
      labels:
        app: todo-app-frontend
    spec:
      containers:
        - name: todo-app-frontend
          image: FRONTEND_IMAGE
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
               path: /health
               port: 80
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            httpGet:
               path: /health
               port: 80
