apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: FRONTEND_IMAGE
  newName: mtuomiko/todo-app-frontend
  newTag: 85940b00d5abe75b4e7a045646378113affb2bcd
