apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: postgres-svc
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres-svc-port
  clusterIP: None
  selector:
    app: postgres-db
