apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      volumes:
        - name: dwk-backend-volume
          emptyDir: {}
      containers:
        - name: todo-app-backend
          image: mtuomiko/todo-app-backend:0.0.7
          volumeMounts:
            - mountPath: /app/data
              name: dwk-backend-volume
          envFrom:
            - configMapRef:
                name: dwk-project-configmap
            - secretRef:
                name: project-secret
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 5600
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            httpGet:
              path: /health
              port: 5600
