apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      volumes:
        - name: dwk-backend-volume
          emptyDir: {}
      containers:
        - name: todo-app-backend
          image: mtuomiko/todo-app-backend:0.0.3
          volumeMounts:
            - mountPath: /app/data
              name: dwk-backend-volume
