apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-db-ss
  namespace: project
spec:
  serviceName: todo-app-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-db
  template:
    metadata:
      labels:
        app: todo-app-db
    spec:
      containers:
        - name: todo-app-db
          image: postgres:alpine
          ports:
            - name: psdb
              containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
              subPath: postgres
          envFrom:
            - configMapRef:
                name: dwk-project-configmap
            - secretRef:
                name: project-secret
          resources:
            limits:
              cpu: "2000m"
              memory: "1024Mi"
  volumeClaimTemplates:
    - metadata:
        name: db-storage
        namespace: project
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi