apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-db-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-db
  template:
    metadata:
      labels:
        app: pingpong-db
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: pingpong-db-claim
      containers:
        - name: pingpong-db
          image: postgres:alpine
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exercises-secret
                  key: DB_PASSWORD
