apiVersion: v1
kind: Service
metadata:
  name: pingpong-db-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: pingpong-db
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
