apiVersion: v1
kind: Service
metadata:
  name: pingpong-db-svc
  namespace: exercises
  labels:
    app: pingpong-db
spec:
  selector:
    app: pingpong-db
  ports:
    - port: 5432
      name: psdb
  clusterIP: None