apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      volumes:
        - name: dwk-backend-volume
          emptyDir: {}
      containers:
        - name: todo-app-backend
          image: PROJECT/BACKEND_IMAGE
          volumeMounts:
            - mountPath: /app/data
              name: dwk-backend-volume
          envFrom:
            - configMapRef:
                name: dwk-project-configmap
            - secretRef:
                name: project-secret
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"