apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc
  namespace: project
  labels:
    app: todo-app-backend
spec:
  type: NodePort
  selector:
    app: todo-app-backend
  ports:
    - port: 5600
      protocol: TCP
      targetPort: 5600
