apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dwk-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: todo-app-frontend-svc
                port:
                  number: 5000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: todo-app-backend-svc
                port:
                  number: 5600
