apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dwk-ingress
  namespace: project
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: todo-app-frontend-svc
              servicePort: 5000
          - path: /api
            backend:
              serviceName: todo-app-backend-svc
              servicePort: 5600
          - path: /api/*
            backend:
              serviceName: todo-app-backend-svc
              servicePort: 5600
