apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticker-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticker
  template:
    metadata:
      labels:
        app: ticker
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: dwk-storage-claim
      containers:
        - name: ticker-generator
          image: mtuomiko/ticker-generator:0.0.1
          volumeMounts:
            - mountPath: /app/shared
              name: shared-data
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
        - name: ticker-server
          image: mtuomiko/ticker-server:0.0.9
          volumeMounts:
            - mountPath: /app/shared
              name: shared-data
          env:
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: dwk-exercises-configmap
                  key: MESSAGE
          resources:
            requests:
              cpu: "200m"
              memory: "32Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            httpGet:
              port: 4000
              path: /health
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - ticker
              topologyKey: kubernetes.io/hostname
