apiVersion: v1
kind: Service
metadata:
  name: ticker-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ticker
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 4000