apiVersion: v1
kind: Service
metadata:
  name: ticker-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: ticker
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000