apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: helm-step
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  path: "./cluster/helm"
  interval: 10m
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: argo-rollouts
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: sealed-secrets
      namespace: flux-system
