apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps-step
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  path: './cluster/apps'
  interval: 10m
  prune: true
  dependsOn:
    - name: infra-step
  validation: none # I give on getting the install order working