apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: helm-step
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  path: './cluster/helm'
  interval: 10m
  prune: true
  validation: none