apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra-step
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  path: './cluster/infra'
  interval: 10m
  prune: true
  dependsOn:
    - name: helm-step
  validation: client