apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: argo-rollouts
  namespace: flux-system
spec:
  interval: 1h
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-rollouts
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: argo-rollouts
      sourceRef:
        kind: HelmRepository
        name: argo-rollouts
        namespace: flux-system
  targetNamespace: argo-rollouts
  releaseName: argo-rollouts
