apiVersion: v1
kind: Pod
metadata:
  name: alpine1
  namespace: project
  labels:
    app: alpine1
spec:
  containers:
  - image: alpine
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always