apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: mtuomiko/pingpong:0.0.4
          envFrom:
            - configMapRef:
                name: pingpong-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pingpong-secret
                  key: DB_PASSWORD
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: exercises
  name: pingpong-config
data:
  DB_HOST: "postgres-svc.default"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "pingpong"
