apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: persistent-shared-dir # used by pingpong and ticker-server
          persistentVolumeClaim:
            claimName: dwk-storage-claim
      containers:
        - name: pingpong
          image: mtuomiko/pingpong:0.0.2
          env:
          - name: COUNT_FILE
            value: "/persistent-shared/count.json"
          volumeMounts:
          - name: persistent-shared-dir
            mountPath: "/persistent-shared"
