apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: persistent-shared-dir # used by pingpong to keep state
          persistentVolumeClaim:
            claimName: dwk-exercises-storage-claim
      containers:
        - name: pingpong
          image: mtuomiko/pingpong:0.0.3
          env:
          - name: COUNT_FILE
            value: "/persistent-shared/count.json"
          volumeMounts:
          - name: persistent-shared-dir
            mountPath: "/persistent-shared"
