apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: todo-generator
  namespace: project
spec:
  schedule: "15 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-generator
              image: GENERATOR_IMAGE
              env:
                - name: TODO_BACKEND_URL
                  valueFrom:
                    configMapKeyRef:
                      name: dwk-project-configmap
                      key: TODO_BACKEND_URL
          restartPolicy: Never
