apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend-svc
  namespace: project
  labels:
    app: todo-app-frontend
spec:
  type: NodePort
  selector:
    app: todo-app-frontend
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 80
