apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticker-generator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticker-generator
  template:
    metadata:
      labels:
        app: ticker-generator
    spec:
      containers:
        - name: ticker-generator
          image: mtuomiko/ticker-generator:0.0.1
          env:
          - name: STATUS_FILE
            value: "/shared/status.json"
