apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
  namespace: project
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: mtuomiko/todo-broadcaster:0.0.9
          envFrom:
            - configMapRef:
                name: dwk-project-configmap
            - secretRef:
                name: project-secret
