apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dwk-storage-claim
  namespace: exercises
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
