apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exercises-secret
  namespace: exercises
spec:
  encryptedData:
    DB_PASSWORD: AgBeflk0GYVnXS79QGR0PixVRwFHBX7kQIz8a2uk4BZ9eG+zkXVzNOQl2bn4A8iOreKQ/Ts0tvZHmXCsbfqy4FaNY4/UzEiNc5+2lrPbNvvgZCxWW8KABeyELafuXicnsCXawC6bDWiWAbUQUWihRsX2yccPbtNVhZhhLOTFsEOdJZDBRE6I2jE+BfD9JTA7jxxwK2uPi8Q6Ze581EIiktre2OD/obE/kvPTjMZXbSdbr1RF5F0NchLCt3xWiSw/ZQ3NPT60nlP7POzA21Km/4u5hWvHkKEwJ65cm9RwMN+SbLo58xCKfG4lPQdRKbxtEyPp1ZjBRMwTE5Y0KHphHnsxNgySOtU5issQ0OfoQEtb5g1GaYMpUhKAQIt1FpzKHTyflWsQ+eBkohRFSBIhUyYgobJr9SMZNKRMBTGZNM4aQ2ziVjOF+JKrbaspzsDPE9xTTXazU9nsgkSEQdbLrzFxiFH04zL3ut6d6J0GGGs2t7pDIh1Q5pfWfbmFwHuz9RK4Kf8cYqX0lxuurB8UIfX+77lv9iPP26ZisEc6Hliey33BSXDTL1+fGjLgm0v4a2S7hAdG8bUUrenKHY4s1KCyItB9LD3elRboIgv2OStVEdxGVgrOtTiPJTIXcA0MJSmkfG+VovvpISkbZHJeBhAnEHrTE2BhcLyWl6/EU59Xkc1MNFlF+dao/QUyORO/Uj+Ks2Otk57ca8cr0sJbQGik4pI=
  template:
    metadata:
      creationTimestamp: null
      name: exercises-secret
      namespace: exercises

