apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: project-secret
  namespace: project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAXn18hlJT3BRvEhaJ5Vit202LiChNTNLbCORdeNf7QHCEYRMvPcVlFop7+t0Nmcs30B0EidtI3NW7n/Nxp2LOE01NUBr3F/0/h3ZkoT3GkkO+ASofaGToQ85QX7V59OutyD7I7yCLiA4rmQfOZVyhQC7vrBreXT/TfbLr+sMJCJA42x3nnqNx0NPJN1MUXyVWUQV8Fy/61nNYRhsgyEGgs6/0vCuVMeV236L5i1+wyZ17l5+pN/Dt/Xg+MDh9Ws/ZT837l6CK+ROGjhGD+Ooahfg42m+aRNIoRSxBEK+p+AiqgRBgF59kh85Q6gaX45Jmgv/cV/GPMZDkflEPQ28XMVOTguWrU74OnEqlhwYKAYiNXEHr/zmh9uH6hBQAH/wib1snOJGYHg3LTSx/dRLDWJeTW0gIHYPGiT6UXuiybcVKS5iaqD30CxZODOhhl0j79H/o2DMIID2KsjfVZlz7kkJJHiu6TnUsiTu0iFNjFVL1l6znCVyNi8LA+isTvIK/V7vK6/rMB7oTdXpbiu4Z/crtANxVDmGRpQ0MhQf6cgtXMK300H9q7nPYsvp6r1HN0mEwRehscAR7/okI2J1OKhgD284TeqWbi4K1AC3r+S4tiqKnIT/E46vM6YooiEQwlGjWiDeF28Cf1/CdSbZC+YUWgpdlvGgK6yRu1fwTobZb+ClXEDk3Ounmh4WTr8TJ/dBhqOyH5eOJtYjkRDvY=
    TELEGRAM_BOT_TOKEN: AgCloVm7wSX/eo8H41gwNOaZoQPUT1ZQzBpDddYoa+D7HF7it/tuYMqDhdxcRw/wa6HxkzuHp05n3pg/dnBvv+mJaS4BnhJ3A1E+foxxvHIHkPcXbNZi5FPOZ5QQaN8rZkdhf0RQUYqGmaHp6AVzSQKhDD4OmwuFcOMnXKoHFBU2m9yjikv84hxjbdABUdmBOFQYjNEJOcsE4l6CZipBgswcPann4zpRHZwCYEt8V1Lt7ZUWwvMjXtmEja2H/tzCGNBI8y1O8RtwA6RsVXODs4cIeeSAZq7xKAPYONMpysx22gZodF4TsH+BktzfbkT8TGSPHRehnjwwxLk1dAlvizgSuowLcByZoxcvcbXpIK0vUVTjwzFDGMdCc5uj3uwGTXTVh/r7P1SP1t6lRf06EG4YrDHAg6mEZJOzNiXqcWU9Jn3av2F5+SvPluCwbVFzw76RsylUlHc62zwL/7N/I0QNU6qRwyoO5YbjntZPFRAB7+2RKkXPMGX55CNuLuWQRZAKWFCp+WBpc0rY+Y3a5SvfpwIbw3vYJhrKT0Ux8ST7hFXVomISkCY/ZJarKJmyA/CPYsNCsXVUm5/7Zsxu4MLOul36H5bU37R3FD8twcDx8Cu70L/3o2x9baNJ3QUKyZrgVa2ALEfwz2TASoet/oL7n7c24+HbJrickGEfORP5X0MrUoqDf/m1sHf5bE3+jDtBskEFDfG6qUzJKnjAcO0F4hA4jt5g/Q2SXW95DUq+7YRPrKsGAxpkb8ju/1Pf
  template:
    metadata:
      creationTimestamp: null
      name: project-secret
      namespace: project

