apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exercises-secret
  namespace: exercises
spec:
  encryptedData:
    DB_PASSWORD: AgCAkLlXxWhMZAVYrwR6M5FWK4F0GAlHn4xD+7DJXLUvBZF6us65It0Z2O/+2nwu/Qz74CDX+qGBGVwenS3HoOwEZDNxJyR3mKR1fI16kymI37BDCO24fi6C4C0zqLmUjtCnmuys7yrcPeHz2wFsVdTCTZQo5Y44sEPrJIgE38LaSrai0G9dLMVqwWZ5j9qgYw+pl59o8mdDYbbH0+Uuj1VFK+UeXjLJnRE1sz3e05u/njDDHS8nulZFuWwx8Po7wNeunNu73YpFjGN9lAQsjQ311l/pc8zjZ8Ei29qdNeFEzukoZ7sS9mAZYj6ztXemjiu1041ykzhvcLw2n/7oWrUHY3uVG85Yw+sdNY7yWhJxDejCAxuakG3hKgyknGSSdaE3JoSp9a98Za5lOfUYBoCagser4UyutTLl/pTEAT+8CEetg9g83PtotBpuVm7gEDCViIsLwtOhZFmyCIGogYT7r4i0XGk4X7gU2bO86xJjR6I3lMNUV/qBYv9YmjYVkui0rDS8rgYZnRKXZNrE1w44Ui/VUtgKWHvJmW0AlIb37DAtbA4+LU2dgrfPsNd8wVDARh+GYQjhiedRw+lixt+ViHF6grfswcdd6NQI9JzdUnIi56S3QgE0iTdV+5h4AuOUT0hKnbaXfAhZI11O/mdYBjjDbCidRAVetcwVHxw7e6xxxNvi7ptA9LqYaehRLNg+vtEjUJn++sm3sAr+4H0SV+o=
  template:
    metadata:
      creationTimestamp: null
      name: exercises-secret
      namespace: exercises

