apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: BROADCASTER_IMAGE
  newName: mtuomiko/todo-broadcaster
  newTag: 605cebb83be447c5b6a6523506a09fcf10a829fb
