FROM golang:1.23.5-alpine as build

WORKDIR /work
COPY go.mod .
COPY go.sum .
RUN go mod download && go mod verify

COPY . .
# CGO_ENABLED=0 to allow using from scratch images
RUN CGO_ENABLED=0 go build

FROM scratch

WORKDIR /app
COPY --from=build /work/todo-app-backend /app/todo-app-backend
ENTRYPOINT ["/app/todo-app-backend"]
