apiVersion: v1
kind: PersistentVolume
metadata:
  name: dwk-project-storage-pv
spec:
  storageClassName: dwk-project-storage
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube-dwk-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0
