apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: dwk-project-storage-claim
spec:
  storageClassName: dwk-project-storage
  volumeName: dwk-project-storage-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
