apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticker-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticker-server
  template:
    metadata:
      labels:
        app: ticker-server
    spec:
      containers:
        - name: ticker-server
          image: mtuomiko/ticker-server:0.0.1
          env:
          - name: STATUS_FILE
            value: "/shared/status.json"
