apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: project-secret
  namespace: project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAZsWx68qgZz3kQKJMenP80BBNzBvTSwWYY9j83ClzVShIBuF5+/a9/sQ697ln5zI10ErnpWZaHaNf19E/bybZeA9Tu5Zyps3v2+d19chfkApGVhSrszfFhTPPUm5nLaw6eT0QPuTqyDD8c9MNO1ARSVZ98VBWwadJvR/EwsmmBMq/Cp82I1JZWSWHrBNtmXQS8xyqDNSO2C0mjYtVOVLCoWhoAvUSFUEj/LvNyjRW7Kgxf2s9mg28NuH/BIq8IADcbRaaZMD19OMgBYkd4nwEa9UXvtlzvDoH+0HPBYkrdbhQMjScmUy/PbM+oZ4MaUU4iaPD2mDAeMM+uk2f2D4Cat0l3RxV5thHMgil+Y9hmLHmJjtSowCu19pnT1VTO7SDnJSRLfKJyqA0JZ+aC2cln50hnTePwZYvW+3XbqAn64/f4uptkH5oj17DiEK9VzOwzedfNCb4Re0JcaiH4RnzdaGnwiVpQj5gC2y8PRHuWp9hzgN1VKQxGw/taKV24D3tNVqNiHqd9bre2bO8O4JKvAiNiTcFXK/1Lvcmpp7HLeWUcG3pS/XPFqaqAqyxu0pMmnPhNF1SGz/WJTQrbLXF3n6W5S8eZOlQzcMVmd3hBqAeVIgkp1gwvqoDH9SqTFGlcly4VO+OkblIo2wc6G4aerWk7aoM3OLunnyBl5kdlJLYs8Xa5OmOVL1r6ljdrAm1zvE0cp4TFD4Wf3DUJfmY=
    TELEGRAM_BOT_TOKEN: AgAilkhlmB2sF2/mN1gdqMB/fXRsP5EZDPWZk8w3DKoCLIFZBPcUreIgCyXiQrJiYdw1Wo1roxT4Q+5M0lnTi0g+0WKNoM6y6SzMQQ1DaROrJLA3/7JjyKXf38pMhJgFjUipHID3aWIVHQuE/VbhBTVY8IwIGmRMfz4SEwwPZi9Z4WDDqss1mWP6f2QEuZxQvgGFQa2Y7mvSWccqqf5boP+7pMN/b5mOS43ngFA8gYLYa1hmnllSw6BLv1txaTfV9ygChlZzFGyVMC4bAovRRLmOpQ75srPNyhuRasGtkiIxl+2uAo3zwT456t/nmaGeNKfjN663g2V9aRysg3JTwXLCkxXZIedbXEHzFbrtyg0aO7ai25TsD4jwi88SdQs9Dce0ZXfnp6nOkTTfTm4bZdN6BeEH66J7d7I3BJmK9cTfaOCOlmTZMN/ijGgK4kDQyvfVRLQ7X+ps6P4tJTgWuT9IycjXVXWJ+/8Knh+qao6uXD7vGyOTLEK3+ki9J/Wsosz+8wpFkBuWM4AMuOppRurOsrB+ycz4zu1734PphdBr0P9TpkhdT6aUgyJGNN7pbkhMjFIAeSjZvN3ePfQFuxj3GDrRkrmed0hEuhdkw0D/CRv0Fev47v06jByVRAUfsfTkLe4su755jC4qUL1KAxcbLuIGibuHVmfhjIuzFbKAf227vW2OfGTc3MTnOksBeUCVuxysUl2d5Oh/U4dALLcii78vQ+q56XP4SsnP53WiUNQ+tvu2okTQGoS4mCay
  template:
    metadata:
      creationTimestamp: null
      name: project-secret
      namespace: project

